### PR TITLE
Adding Async Suggestion fetch

### PR DESCRIPTION
**Pull request by DmitryDodzin**
Wanted to add the ability to async fetch the suggestions, meaning using a function with a callback or Promise

### CODE REVIEW

**Comment by gregchamberlain** [comment]
Great feature addition, the base functionality looks great, thanks! Could you update the two examples to call toLowerCase() on the value and suggestion when filtering to make them consistent with the existing examples? Once those are updated I'd be more than happy to merge it.

**Comment by DmitryDodzin** [comment]
Ok, I have a consideration. Should the unique affect the results from the async fetch or should the async be as is?

**Comment by gregchamberlain** [comment]
Good catch. Unique should affect the result, we shouldn't be showing a result that won't get added if selected (in the case where a chip already exists for the result).

**Comment by DmitryDodzin** [comment]
I did the backmerge and added the uniqueChips for async fetch.

**Pull request merged**
